#!/usr/bin/env python3
"""Inject SEO metadata into every page.

Idempotent: the block is delimited by markers and replaced wholesale on each
run, so this can be re-run after the page generators without duplicating tags.
Existing <title> and <meta name="description"> are never rewritten — they are
read and reused for the social tags.

Run from the repo root:  python3 scripts/add_seo.py
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://dragonkingsutra.org"
OG_IMAGE = f"{SITE}/assets/og-image.jpg"
BEGIN = "<!-- SEO:begin (generated by scripts/add_seo.py — do not edit by hand) -->"
END = "<!-- SEO:end -->"

SUTRA_TITLE = "The Sutra Spoken by the Buddha on the Sea Dragon King"
GURU = "His Holiness Living Buddha Lian Sheng"

# page -> (og:type, priority, changefreq, extra JSON-LD builder key)
PAGES = {
    "index.html":        ("website", "1.0", "monthly", "home"),
    "read.html":         ("article", "0.9", "yearly",  "book"),
    "about.html":        ("article", "0.8", "yearly",  "about"),
    "treasure-vase-yoga.html":   ("article", "0.8", "yearly", "practice"),
    "treasure-vase-wishes.html": ("article", "0.7", "yearly", "wishes"),
    "his-holiness-living-buddha-lian-sheng.html": ("profile", "0.7", "yearly", "person"),
    "refuge.html":       ("article", "0.7", "yearly",  "page"),
    "contact.html":      ("website", "0.4", "yearly",  "page"),
}
NOINDEX = {"404.html"}


def organization():
    return {
        "@type": "Organization",
        "name": "True Buddha School",
        "url": "https://en.tbsn.org/",
    }


def person_guru():
    return {
        "@type": "Person",
        "name": GURU,
        "alternateName": ["Grandmaster Sheng-Yen Lu", "Lian Sheng", "蓮生活佛", "盧勝彥"],
        "jobTitle": "Root Guru of the True Buddha School",
        "birthDate": "1945",
        "birthPlace": {"@type": "Place", "name": "Chiayi, Taiwan"},
        "affiliation": organization(),
        "url": f"{SITE}/his-holiness-living-buddha-lian-sheng",
    }


def website():
    return {
        "@type": "WebSite",
        "@id": f"{SITE}/#website",
        "url": SITE + "/",
        "name": "Dragon King Sutra",
        "alternateName": "佛說海龍王經",
        "inLanguage": ["en", "zh-Hant"],
        "publisher": organization(),
    }


def book():
    return {
        "@type": "Book",
        "@id": f"{SITE}/#sutra",
        "name": SUTRA_TITLE,
        "alternateName": ["佛說海龍王經", "Sāgara-nāgarāja-paripṛcchā Sūtra"],
        "translator": {"@type": "Person", "name": "Dharmarakṣa", "alternateName": "竺法護"},
        "inLanguage": ["zh-Hant", "en"],
        "genre": "Mahayana Buddhist scripture",
        "numberOfPages": 4,
        "about": [
            {"@type": "Thing", "name": "Mahayana Buddhism"},
            {"@type": "Thing", "name": "Dragon Kings"},
            {"@type": "Thing", "name": "Vajrayana"},
        ],
        "url": f"{SITE}/read",
    }


def article(url, headline, description, author_is_guru=True, image=OG_IMAGE):
    node = {
        "@type": "Article",
        "headline": headline,
        "description": description,
        "image": image,
        "url": url,
        "isPartOf": {"@id": f"{SITE}/#website"},
        "inLanguage": "en",
    }
    if author_is_guru:
        node["author"] = person_guru()
    return node


def breadcrumb(*crumbs):
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": url}
            for i, (name, url) in enumerate(crumbs)
        ],
    }


def jsonld_for(key, page, url, title, desc):
    """Returns the @graph list for a page."""
    if key == "home":
        return [website(), book(), person_guru()]
    if key == "book":
        b = book()
        b["description"] = desc
        return [website(), b,
                breadcrumb(("Home", SITE + "/"), ("Read the Sutra", url))]
    if key == "about":
        return [article(url, title, desc, author_is_guru=False),
                {"@type": "Book", "@id": f"{SITE}/#sutra"},
                breadcrumb(("Home", SITE + "/"), ("About the Sutra", url))]
    if key == "practice":
        a = article(url, "The Dragon King Treasure Vase Yoga", desc)
        a["about"] = {"@type": "Thing", "name": "Dragon King Treasure Vase Yoga 龍王寶瓶法"}
        return [a, breadcrumb(("Home", SITE + "/"), ("Practice", url))]
    if key == "wishes":
        a = article(url, "Wishes in the Dragon King Treasure Vase Practice", desc)
        a["isPartOf"] = {"@type": "Book", "name": "A Solitary Bird in the Void",
                         "alternateName": "虛空中的孤鳥", "bookEdition": "Book 146",
                         "author": person_guru()}
        return [a, breadcrumb(("Home", SITE + "/"), ("Wishes in the Treasure Vase", url))]
    if key == "person":
        return [person_guru(),
                breadcrumb(("Home", SITE + "/"), (GURU, url))]
    return [{"@type": "WebPage", "url": url, "name": title, "description": desc,
             "isPartOf": {"@id": f"{SITE}/#website"}, "inLanguage": "en"}]


def json_dumps(obj, indent=2):
    """Minimal deterministic JSON writer (keeps key order, escapes for <script>)."""
    import json
    text = json.dumps(obj, ensure_ascii=False, indent=indent)
    # a literal </script> inside JSON-LD would close the tag early
    return text.replace("</", "<\\/")


def canonical_path(page):
    """about.html -> /about   (html_handling: auto-trailing-slash serves both)"""
    if page == "index.html":
        return "/"
    return "/" + page[:-len(".html")]


def build_block(page, title, desc):
    if page in NOINDEX:
        return (f'{BEGIN}\n'
                f'<meta name="robots" content="noindex, follow">\n'
                f'<meta name="theme-color" content="#070e1a">\n'
                f'{END}')

    og_type, _prio, _freq, key = PAGES[page]
    url = SITE + canonical_path(page)
    graph = jsonld_for(key, page, url, title, desc)
    ld = {"@context": "https://schema.org", "@graph": graph}

    t = html.escape(title, quote=True)
    d = html.escape(desc, quote=True)
    lines = [
        BEGIN,
        f'<link rel="canonical" href="{url}">',
        '<meta name="robots" content="index, follow, max-image-preview:large">',
        '<meta name="theme-color" content="#070e1a">',
        '',
        f'<meta property="og:type" content="{og_type}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:title" content="{t}">',
        f'<meta property="og:description" content="{d}">',
        f'<meta property="og:image" content="{OG_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="A golden dragon coiled around a flaming pearl beneath a radiant Buddha — {html.escape(SUTRA_TITLE, quote=True)}">',
        '<meta property="og:site_name" content="Dragon King Sutra">',
        '<meta property="og:locale" content="en_US">',
        '<meta property="og:locale:alternate" content="zh_TW">',
        '',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{t}">',
        f'<meta name="twitter:description" content="{d}">',
        f'<meta name="twitter:image" content="{OG_IMAGE}">',
        '',
        f'<script type="application/ld+json">\n{json_dumps(ld)}\n</script>',
        END,
    ]
    return "\n".join(lines)


TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
DESC_RE = re.compile(r'<meta name="description" content="(.*?)">', re.S)


def process(path: Path) -> str:
    s = path.read_text(encoding="utf-8")
    page = path.name

    m = TITLE_RE.search(s)
    if not m:
        return f"{page}: no <title>, skipped"
    title = html.unescape(m.group(1).strip())
    dm = DESC_RE.search(s)
    desc = html.unescape(dm.group(1).strip()) if dm else title

    block = build_block(page, title, desc)

    # replace an existing block, else insert before the icon link (stable anchor)
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, s, flags=re.S)
        action = "updated"
    else:
        anchor = '<link rel="icon"'
        assert anchor in s, f"{page}: no icon link to anchor to"
        s = s.replace(anchor, block + "\n" + anchor, 1)
        action = "inserted"

    path.write_text(s, encoding="utf-8")
    return f"{page}: {action}"


def sitemap():
    urls = []
    for page, (_t, prio, freq, _k) in PAGES.items():
        urls.append(
            "  <url>\n"
            f"    <loc>{SITE}{canonical_path(page)}</loc>\n"
            f"    <changefreq>{freq}</changefreq>\n"
            f"    <priority>{prio}</priority>\n"
            "  </url>"
        )
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + "\n".join(urls) + "\n</urlset>\n")
    (ROOT / "sitemap.xml").write_text(xml, encoding="utf-8")
    return f"sitemap.xml: {len(PAGES)} urls"


def robots():
    txt = ("User-agent: *\n"
           "Allow: /\n"
           "\n"
           f"Sitemap: {SITE}/sitemap.xml\n")
    (ROOT / "robots.txt").write_text(txt, encoding="utf-8")
    return "robots.txt written"


if __name__ == "__main__":
    for page in list(PAGES) + sorted(NOINDEX):
        print(" ", process(ROOT / page))
    print(" ", sitemap())
    print(" ", robots())
